sudoers_rewrite_default_sudoers_file: True
sudoers_remove_unauthorized_included_files: True
sudoers_backup: False
sudoers_files:
  - path: "/etc/sudoers"
    defaults:
      - "requiretty"
      - "!visiblepw"
      - "always_set_home"
      - "env_reset"
      - secure_path:
          - "/sbin"
          - "/bin"
          - "/usr/sbin"
          - "/usr/bin"
      - env_keep:
          - "COLORS"
          - "DISPLAY"
          - "HOSTNAME"
          - "HISTSIZE"
          - "INPUTRC"
          - "KDEDIR"
          - "LS_COLORS"
          - "MAIL"
          - "PS1"
          - "PS2"
          - "QTDIR"
          - "USERNAME"
          - "LANG"
          - "LC_ADDRESS"
          - "LC_CTYPE"
          - "LC_COLLATE"
          - "LC_IDENTIFICATION"
          - "LC_MEASUREMENT"
          - "LC_MESSAGES"
          - "LC_MONETARY"
          - "LC_NAME"
          - "LC_NUMERIC"
          - "LC_PAPER"
          - "LC_TELEPHONE"
          - "LC_TIME"
          - "LC_ALL"
          - "LANGUAGE"
          - "LINGUAS"
          - "_XKB_CHARSET"
          - "XAUTHORITY"

    user_specifications:
      - users: 
          - root
          - '%ops'
          - OPS
        hosts: 
          - ALL
        commands: 
          - ALL
        operators:
          - ALL
    
      - users:
          - ANSIBLE
        hosts:
          - ALL
        commands:
          - ALL
        operators:
          - ALL
#        tags:
#          - ALL

    aliases:
      user_alias:
        - name: "OPS"
          users:
            - "mokuno"
            - "josh"

        - name: "ANSIBLE"
          users:
            - josh
