---
- hosts: github_runner_node
  become: yes

  environment:
    http_proxy: http://10.3.100.201:3128
    https_proxy: http://10.3.100.201:3128

  vars:
    hide_sensitive_logs: false
    docker_server_proxy_settings:
      - "NO_PROXY=vcenter.library.ucsb.edu,vsphere.library.ucsb.edu"
      - "HTTP_PROXY=http://10.3.100.201:3128"
      - "HTTPS_PROXY=http://10.3.100.201:3128"

  roles:

    - role: library.core.yum_config
      tags:
        - role:gha_runners:init
        - stage:init:yum

    - role: library.core.epel
      tags: 
        - role:gha_runners:init
        - stage:init:epel

    - role: singleplatform-eng.users    
      tags: 
        - stage:init:user
        - stage:init:users
        - stage:init:groups

    - role: ahuffman.sudoers
      tags: 
        - role:gha_runners:sudo
        - role:gha_runners:sudoers

    - role: willshersystems.sshd
      tags: [ 'service:sshd', 'stage:init' ]

    - role: geerlingguy.ntp
      tags: 
        - role:gha_runners:ntp
        - role:gha_runners:ntpd
        - never

    - role: sbaerlocher.snmp
      tags: 
        - role:gha_runners:snmp

    - role: geerlingguy.firewall
      tags:
        - role:gha_runners:firewall

    - role: geerlingguy.docker
      tags: 
        - role:gha_runners:docker

    - role: monolithprojects.github_actions_runner
      environment:
        http_proxy: http://10.3.100.201:3128
        https_proxy: http://10.3.100.201:3128
        no_proxy: "vcenter.library.ucsb.edu,vsphere.library.ucsb.edu"
      tags:
        - role:gha_runners:github
        - role:gha_runners:github-actions
        - role:gha_runners:github-actions-runner

  tasks:
     
    - name: construct docker systemd unit file with Environment Variables
      ansible.builtin.template:
        src: templates/docker.service.j2
        dest: /usr/lib/systemd/system/docker.service
        owner: root 
        group: root 
        mode: 0644
      tags:
        - role:gha_runners:docker

    - name: reload systemd configs  
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: docker.service
      tags:
        - role:gha_runners:docker


    - name: ensure ansible is installed
      package:
        name: ansible
        state: latest
      tags:
        - role:gha_runners:ansible

